# Artificial Neural Network

## Importing Libraries

In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [5]:
tf.__version__

'2.1.0'

### Part 1 Data Preprocessing

Importing the dataset

In [6]:
dataset = pd.read_csv("Churn_Modelling.csv")
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:,-1].values

In [7]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
print(y)

[1 0 1 ... 1 1 0]


Encoding categorical data

Label encoding of Gender column

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [10]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the Georgraphy column

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [13]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the dataset into training and test set

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0) 

## Feature Scaling

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [16]:
print(x_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


## Building the ANN

### Initializing the ANN

In [17]:
ann = tf.keras.models.Sequential()

### Adding the first input layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

In [20]:
ann.add(tf.keras.la​ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))yers.Dense(units = 6,activation = 'relu'))


In [21]:
ann.add(tf.keras.layers.Dense(units=1, activation = 'sigmoid'))

Training the ANN

Compiling the ANN

In [25]:
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

##Training the ANN

In [26]:
ann.fit(x_train,y_train, batch_size = 32, epochs= 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 3s 318us/sample - loss: 0.5491 - accuracy: 0.7931
Epoch 2/100
8000/8000 [==============================] - 0s 44us/sample - loss: 0.4778 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 40us/sample - loss: 0.4487 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 0s 46us/sample - loss: 0.4342 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 0s 40us/sample - loss: 0.4281 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 0s 51us/sample - loss: 0.4250 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 0s 44us/sample - loss: 0.4222 - accuracy: 0.8060
Epoch 8/100
8000/8000 [==============================] - 0s 41us/sample - loss: 0.4199 - accuracy: 0.8163
Epoch 9/100
8000/8000 [==============================] - 0s 40us/sample - loss: 0.4177 - accuracy: 0.8184
Epoch 10/100
8000/8000 

8000/8000 [==============================] - 0s 50us/sample - loss: 0.3359 - accuracy: 0.8655
Epoch 78/100
8000/8000 [==============================] - 0s 45us/sample - loss: 0.3353 - accuracy: 0.8633
Epoch 79/100
8000/8000 [==============================] - 0s 47us/sample - loss: 0.3353 - accuracy: 0.8636
Epoch 80/100
8000/8000 [==============================] - 0s 53us/sample - loss: 0.3349 - accuracy: 0.8641
Epoch 81/100
8000/8000 [==============================] - 0s 59us/sample - loss: 0.3353 - accuracy: 0.8639
Epoch 82/100
8000/8000 [==============================] - 0s 44us/sample - loss: 0.3351 - accuracy: 0.8641
Epoch 83/100
8000/8000 [==============================] - 0s 46us/sample - loss: 0.3350 - accuracy: 0.8635
Epoch 84/100
8000/8000 [==============================] - 0s 48us/sample - loss: 0.3345 - accuracy: 0.8648
Epoch 85/100
8000/8000 [==============================] - 0s 44us/sample - loss: 0.3350 - accuracy: 0.8652
Epoch 86/100
8000/8000 [==========================

Making the prediction and evaluating the model

Prediecting the result of a single observation

In [28]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40 , 3, 60000, 2, 1 , 1 , 50000]]))>0.5)

[[False]]


Predicting the Test Results

In [29]:
y_pred = ann.predict(x_test)
y_pred = (y_pred >0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making the Confusion Matrix

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1510   85]
 [ 191  214]]


0.862